spring:
  application:
    name: catalog-service
  datasource:
    username: root
    password: Oea75357@
    url: jdbc:mysql://localhost:3307/catalog?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    show-sql: true


catalog:
  page-size: 10

  exchange-name: exchange-name

  borrow-book-queue: borrowed-book-queue
  returned-book-queue : returned-book-queue
  new-book-queue : new-book-queue


server:
  port: 8081
  shutdown: GRACEFUL
