services:
  catalog-db:
    container_name: catalog-db
    image: mysql:latest
    networks:
      - catalog_network
    volumes:
      - catalog_final_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Oea75357@
      MYSQL_DATABASE: catalog
    ports:
      - "3307:3306"
    depends_on:
      - rabbitmq


  user-db:
    container_name: user-db
    image: mysql:latest
    networks:
      - user_network
    volumes:
      - user_final_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Oea75357@
      MYSQL_DATABASE: user
    ports:
      - "3308:3306"
    deploy:
      resources:
        limits:
          memory: 1G

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - catalog_network
      - user_network
    ports:
      - "5672:5672"   # AMQP protocol port for applications
      - "15672:15672" # RabbitMQ Management Dashboard web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Oea75357@

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  catalog_final_data:
    driver: local
  user_final_data:
    driver: local
  rabbitmq_data:

networks:
  catalog_network:
    driver: bridge
  user_network:
    driver: bridge
