services:
#  CATALOG -SERVICES
  catalog-db:
    container_name: catalog-db
    image: mysql
    networks:
      - catalog_network
      -
    volumes:
      - var:lib/var/app/db

    environment:
      - MYDQL_password: Oea75357@
      - MYSQL_USER: root
      - MYSQL_URL: jdbc:mysql:catalog-db://3306/mysql

    ports:
      - 3306:3306

  catalog-service:
    image: mcmanuel295/csi
    container_name: catalog-service
    ports:
      - 8081:8081

    depends_on:
      - catalog-db:
          condition: service-healthy
    restart: unless-stopped

    networks:
      -catalog_network
    


  rabbitMq:
    container_name: rabbit-mq
    image: rabbit.3.12.11-management

    environment:
      - RABBITMQ_DEFAULT_USER: user
      - RABBITMQ_DEFAULT_PASS: password

    ports:
      - 15672:15672
      - 5672:5672



volumes:
  var:
    driver: local


networks:
  catalog_network:
    driver: bridge