services:
  catalog-db:
    container_name: catalog-db
    image: mysql:latest
    networks:
      - catalog_network
    volumes:
      - catalog_final_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Oea75357@
      MYSQL_DATABASE: catalog
    ports:
      - "3307:3306"

  user-db:
    container_name: user-db
    image: mysql:latest
    networks:
      - user_network
    volumes:
      - user_final_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Oea75357@
      MYSQL_DATABASE: user
    ports:
      - "3308:3306"
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  catalog_final_data:
    driver: local
  user_final_data:
    driver: local

networks:
  catalog_network:
    driver: bridge
  user_network:
    driver: bridge
