spring:
  application:
    name: shared

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:Oea75357@}