spring:
  application.name: LibraryManagementSystem

  datasource:
    password: Oea75357@
    url: jdbc:mysql:localhost:3306/LibraryManagementSystemApplication
    username: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


