spring:
  application:
    name: Bookservice

  datasource:
    password: ${DB_PASSWORD:Oea75357@}
    username: ${DB_USER:root}
    url: ${DB_URL:lo}
    driver-class-name: com.jdbc.mysql.

server:
  port: 8082
  shutdown: GRACEFUL