spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service

  datasource:
    username: root
    password: Oea75357@
    url: jdbc:mysql://localhost:3308/user?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_POR}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8082
  shutdown: graceful

user:
  page-no: 0
  size : 10
  sort: title