spring:
  application.name: user-service

  datasource:
    password: Oea75357@
    url: jdbc:mysql://localhost:3307/user?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
  shutdown: GRACEFUL


user:
  page-no: 0
  size : 10
  sort: title