spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service

  datasource:
    username: root
    password: Oea75357@
    url: jdbc:mysql://localhost:3308/user?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:Oea75357@}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


server:
  port: 8082
  shutdown: graceful

user:
  page-no: 0
  size : 10
  sort: title

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    circuitbreakers:
      enabled: true
    mail:
      enabled: false

  endpoint:
    health:
      show-details: ALWAYS


resilience4j:
  circuitbreaker:
    instances:
      catalog:
        automatic-transition-from-open-to-half-open-enabled: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        sliding-window-size: 2
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 15s


  timelimiter:
    instances:
      catalog:
        timeout-duration: 4s
