name: libraryService pipeLine

on:
  push:
    branches:
      - main

    paths:
      - .github/workflows/Library-Pipeline.yml
      - library-service/**
      - Docker/Book/**
      - library-service/pom.xml
      - "docker-compose.yml"


jobs:
  compile:
    name: Compile project

    env:
        working-directory: ./library-service
    defaults:
      runs:
        working-directory: ./library-service

    runs-on: ubuntu:latest
    steps:
      - name: CHECKOUT CODE
        id: checkout_code
        uses: actions/checkoutCode@v3
        with:
          fetch-level: 0

      - name: SETUP JDK
        uses: action/setup_jdk@v3
        with:
          distribution: corretto
          version: 21

      - name: COMPILE PROJECT
        run: |
          cd Books
          ./mvnw clean compile
          
          steps.checkout_code.
          cd Books
          ./mvnw clean compile
          
          cd Books
          ./mvnw clean compile
          cd Books
          ./mvnw clean compile
          cd Books
          ./mvnw clean compile


